# used for development purposes

services:
  nginx:
    image: nginx
    ports:
      - 5000:5000
    extra_hosts:
      host.docker.internal: 192.168.0.254
    network_mode: bridge
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html/:/etc/nginx/html/